routes/web.php
<?php


use App\Http\Controllers\Backend\AdminController;
use App\Http\Controllers\Backend\AdmissionController;
use App\Http\Controllers\Backend\ApplyDateController;
use App\Http\Controllers\Backend\CreteriaController;
use App\Http\Controllers\Backend\DownloadController;
use App\Http\Controllers\Backend\ForgotPasswordController;
use App\Http\Controllers\Backend\RequestController;
use App\Http\Controllers\Backend\StudentApplicationController;
use App\Http\Controllers\Backend\StudentController;
use App\Http\Controllers\Backend\StudentRegisterController;
use App\Http\Controllers\Backend\SiddrankingController;
use App\Http\Controllers\Backend\SocrankingController;

// use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UploadfileController;
use App\Models\ApplyDate;
use App\Models\Student;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () { return view('student.login');});
Route::get('/student/login', [StudentRegisterController::class, 'login'])->name('studentLogin');

require __DIR__.'/auth.php';

Route::middleware(['auth','role:admin'])->group(function () {
    Route::get('/admin/dashboard', function () {return view('admin.dashboard');})->name('dashboard');
    Route::get('/admin/upload', function () {return view('admin.upload');})->name('upload');
    Route::post('import-data',[UploadfileController::class, 'import'])->name('import-data');

    //Display Admission Officers, ranking and students
    Route::get('/admin/socLayout',[StudentController::class,'socView'])->name('socLayout');
    Route::get('/admin/sidLayout',[StudentController::class,'sidView'])->name('sidLayout');
    Route::get('/admin/aoLayout', function () {return view('admin.aoLayout');})->name('aoLayout');
    Route::get('/admin/studentLayout', [AdminController::class, 'displayStudent'])->name('studentLayout');
    Route::get('/admin/creteriaLayout', function () {return view('admin.creteriaLayout');})->name('creteriaLayout');
    Route::get('/admin/requestLayout', function () {return view('admin.requestLayout');})->name('requestLayout');
    Route::get('/admin/viewAll', [AdminController::class, 'viewAllPage'])->name('viewAll');
    Route::get('/admin/dateLayout', function () {return view('admin.dateLayout');})->name('dateLayout');

    //Delete all student data
    Route::delete('/students/deleteAll', [AdminController::class,'deleteAllStudents'])->name('deleteAllStudent');

    //Creteria
    Route::get('/admin/createCreteria', [CreteriaController::class, 'viewPost'])->name('viewCreateCreteria');
    Route::post('/admin/createCreteria', [CreteriaController::class, 'creteriaPost'])->name('createCreteria');
    Route::get('/admin/creteria/{id}', [CreteriaController::class, 'viewCreteria'])->name('viewCreteria');
    Route::delete('/admin/creteria/{id}', [CreteriaController::class, 'deleteCreteria'])->name('deleteCreteria');
    Route::get('/admin/creteria/{id}/edit', [CreteriaController::class, 'editCreteria'])->name('editCreteria');
    Route::put('/admin/creteria/{id}', [CreteriaController::class, 'updateCreteria'])->name('updateCreteria');

    //Feedback
    Route::get('/admin/feedback', [AdminController::class, 'viewFeedback'])->name('feedback');
    Route::delete('/admin/feedback/{id}', [AdminController::class, 'deleteFeedback'])->name('deleteFeedback');

    //Search
    Route::get('/admin/searchStudentLayout', [StudentController::class, 'searchStudent'])->name('searchStudentByIndex');
    Route::get('/admin/searchViewAll', [StudentController::class, 'searchSoc'])->name('searchSocByIndex');

    // Student routes
    Route::get('/admin/createStudent', [StudentController::class, 'viewCreateStudent'])->name('createStudent');
    Route::post('/admin/createStudent', [StudentController::class, 'studentPost'])->name('student');
    Route::get('/admin/studentLayout/{INDEX_NO}', [StudentController::class, 'viewStudent'])->name('viewStudent');
    Route::delete('/admin/studentLayout/{INDEX_NO}', [StudentController::class, 'deleteStudent'])->name('deleteStudent');
    Route::get('/admin/studentLayout/{INDEX_NO}/edit', [StudentController::class, 'editStudent'])->name('editStudent');
    Route::put('/admin/studentLayout/{INDEX_NO}', [StudentController::class, 'updateStudent'])->name('updateStudent');

    // Admission Officer routes
    Route::get('/admin/createAdmissionOfficer', [AdminController::class, 'viewAo'])->name('createAo');
    Route::post('/admin/createAdmissionOfficer', [AdminController::class, 'admissionOfficerPost'])->name('admissionOfficer');
    Route::get('/admin/aoLayout/{cid}', [AdminController::class, 'viewAdmissionOfficer'])->name('viewAdmissionOfficer');
    Route::delete('/admin/aoLayout/{cid}', [AdminController::class, 'deleteAdmissionOfficer'])->name('deleteAdmissionOfficer');
    Route::get('/admin/aoLayout/{cid}/edit', [AdminController::class, 'editAdmissionOfficer'])->name('editAdmissionOfficer');
    Route::put('/admin/aoLayout/{cid}', [AdminController::class, 'updateAdmissionOfficer'])->name('updateAdmissionOfficer');

    //Request
    Route::get('/admin/requestLayout/{INDEX_NO}', [RequestController::class, 'viewRequest'])->name('viewRequest');
    Route::delete('/admin/requestLayout/{INDEX_NO}', [RequestController::class, 'deleteRequest'])->name('deleteRequest');
    Route::get('/admin/requestLayout/{INDEX_NO}/edit', [RequestController::class, 'editRequest'])->name('editRequest');
    Route::put('/admin/requestLayout/{INDEX_NO}', [RequestController::class, 'updateRequest'])->name('updateRequest');

    //soc
    Route::get('/admin/socLayout/{INDEX_NO}', [StudentController::class, 'viewSoc'])->name('viewSoc');
    Route::get('/admin/socLayout/{INDEX_NO}/edit', [StudentController::class, 'editSoc'])->name('editSoc');
    Route::put('/admin/socLayout/{INDEX_NO}', [StudentController::class, 'updateSoc'])->name('updateSoc');

    //sidd
    Route::get('/admin/sidLayout/{INDEX_NO}', [StudentController::class, 'viewSid'])->name('viewSid');
    Route::get('/admin/sidLayout/{INDEX_NO}/edit', [StudentController::class, 'editSid'])->name('editSid');
    Route::put('/admin/sidLayout/{INDEX_NO}', [StudentController::class, 'updateSid'])->name('updateSid');

    //Download
    Route::get('/admin/downloadSoc', [DownloadController::class, 'downloadSoc'])->name('downloadSoc');
    Route::get('/admin/downloadSidd', [DownloadController::class, 'downloadSidd'])->name('downloadSidd');
    Route::get('/admin/downloadAll', [DownloadController::class, 'downloadAll'])->name('downloadAll');

    //Date
    Route::get('/admin/createDate', [ApplyDateController::class, 'viewCreateDate'])->name('createDate');
    Route::post('/admin/createDate', [ApplyDateController::class, 'datePost'])->name('date');
    Route::delete('/admin/dateLayout/{id}', [ApplyDateController::class, 'deleteDate'])->name('deleteDate');
    Route::get('/admin/dateLayout/{id}/edit', [ApplyDateController::class, 'editDate'])->name('editDate');
    Route::put('/admin/dateLayout/{id}', [ApplyDateController::class, 'updateDate'])->name('updateDate');

});

Route::middleware(['auth','role:ao'])->group(function () {
    Route::get('/admission/dashboard', function () {return view('admission.dashboard');})->name('aoDashboard');
    Route::get('/admission/admissionOfficerSocLayout', function () {return view('admission.admissionOfficerSocLayout');})->name('admissionOfficerSocLayout');
    Route::get('/admission/admissionOfficerSidLayout', function () {return view('admission.admissionOfficerSidLayout');})->name('aoSidLayout');
    Route::get('/admission/admissionOfficerStudentLayout', function () {return view('admission.admissionOfficerStudentLayout');})->name('admissionOfficerStudentLayout');

    //student
    Route::get('/admission/admissionOfficerStudentLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerViewStudent'])->name('admissionOfficerViewStudent');
    Route::delete('/admission/admissionOfficerStudentLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerDeleteStudent'])->name('admissionOfficerDeleteStudent');
    Route::get('/admission/admissionOfficerStudentLayout/{INDEX_NO}/edit', [AdmissionController::class, 'admissionOfficerEditStudent'])->name('admissionOfficerEditStudent');
    Route::put('/admission/admissionOfficerStudentLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerUpdateStudent'])->name('admissionOfficerUpdateStudent');

    Route::get('/admission/admissionOfficerSocLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerViewSoc'])->name('admissionOfficerViewSoc');
    Route::get('/admission/admissionOfficerSocLayout/{INDEX_NO}/edit', [AdmissionController::class, 'admissionOfficerEditSoc'])->name('admissionOfficerEditSoc');
    Route::put('/admission/admissionOfficerSocLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerUpdateSoc'])->name('admissionOfficerUpdateSoc');

    Route::get('/admission/admissionOfficerSidLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerViewSid'])->name('admissionOfficerViewSid');
    Route::get('/admission/admissionOfficerSidLayout/{INDEX_NO}/edit', [AdmissionController::class, 'admissionOfficerEditSid'])->name('admissionOfficerEditSid');
    Route::put('/admission/admissionOfficerSidLayout/{INDEX_NO}', [AdmissionController::class, 'admissionOfficerUpdateSid'])->name('admissionOfficerUpdateSid');

    //Download
    Route::get('/admin/downloadAdmissionOfficerSoc', [DownloadController::class, 'downloadAoSoc'])->name('downloadAoSoc');

app/Http/Controllers/Backend/StudentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Student;
use App\Models\feedback;

class StudentController extends Controller
{
    public function viewAllStudents()
    {
        return view('admin.viewAll');
    }

    public function viewCreateStudent()
    {
        return view('admin.createStudent');
    }

    public function viewStudent($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();
        return view('admin.viewStudent', ['student' => $student]);
    }

    public function studentPost(Request $request) {
        $student = new Student();

        $student->INDEX_NO = $request->INDEX_NO;
        $student->CID = $request->CID;
        $student->NAME = $request->NAME;
        $student->DOB = $request->DOB;
        $student->SCHOOL = $request->SCHOOL;
        $student->year = $request->year;

        $student->SUB1 = 'ENG';
        $student->MKS1 = $request->eng;
        $student->SUB2 = 'MAT';
        $student->MKS2 = $request->math;
        $student->SUB3 = 'DZO';
        $student->MKS3 = $request->dzo;
        $student->SUB4 = $request->sub4_name;
        $student->MKS4 = $request->sub4;
        $student->SUB5 = $request->sub5_name;
        $student->MKS5 = $request->sub5;
        $student->SUB6 = $request->sub6_name;
        $student->MKS6 = $request->sub6;
        $student->status = 'approved';

        $values = [$request->dzo, $request->sub4, $request->sub5, $request->sub6];

        rsort($values);
        $top3Values = array_slice($values, 0, 3);
        $totalMarks = ($request->math * 5) + ($request->eng * 2) + array_sum($top3Values);
        $student->TOTAL = $totalMarks;

        $student->save();

        return redirect()->route('studentLayout')->with('success', 'Student successfully added.');
    }

    public function deleteStudent($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        if ($student) {
            $student->delete();
            return redirect()->back()->with('success', 'Student deleted successfully.');
        } else {
            return redirect()->back()->with('error', 'Student not found.');
        }
    }

    public function editStudent($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        return view('admin.editStudent', ['student' => $student]);
    }

    public function updateStudent(Request $request, $INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        if ($student) {
            $student->update($request->all());
            return redirect()->back()->with('success', 'Student updated successfully.');
        } else {
            return redirect()->back()->with('error', 'Student not found.');
        }
    }

    //Search for Admin
    // public function searchStudent(Request $request){
    //     $query = $request->input('query');

    //     $studentsQuery = Student::where('ELIGIBILITY', 'Eligible')->orderBy('TOTAL');

    //     if (!empty($query)) {
    //         $studentsQuery = $studentsQuery->where('INDEX_NO', 'like', '%' . $query . '%');
    //     }

    //     $students = $studentsQuery->get();

    //     return view('admin.studentLayout', compact('students'));
    // }
    public function searchStudent(Request $request){
        $query = $request->input('query');

        $studentsQuery = Student::where('ELIGIBILITY', 'Eligible')->orderBy('TOTAL');

        if (!empty($query)) {
            $studentsQuery = $studentsQuery->where('INDEX_NO', 'like', '%' . $query . '%');
        }

        $students = $studentsQuery->get();

        return view('admin.studentLayout', compact('students'));
    }

    public function searchSoc(Request $request){
        $query = $request->input('query');

        $studentsQuery = Student::orderBy('TOTAL');

        if (!empty($query)) {
            $studentsQuery = $studentsQuery->where('INDEX_NO', 'like', '%' . $query . '%');
        }

        $students = $studentsQuery->get();

        return view('admin.viewAll', compact('students'));
    }

    public function viewContactUs() {
        return view('student.contactUs');
    }

    public function feedbackPost(Request $request) {

        $feedback = new feedback();

        $request->validate([
            'name' => 'required',
            'message' => 'required',
        ]);

        $feedback->name = $request->name;
        $feedback->email = auth()->user()->email;
        $feedback->message = $request->message;

        $feedback->save();

        return redirect()->route('studentDashboard')->with('form2_success', 'Feedback successfully sent.');
    }

    //SOC
    public function viewSoc($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();
        return view('admin.viewSoc', ['student' => $student]);
    }

    public function editSoc($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        return view('admin.editSoc', ['student' => $student]);
    }

    public function updateSoc(Request $request, $INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        if ($student) {
            $student->update($request->all());
            return redirect()->back()->with('success', 'Student updated successfully.');
        } else {
            return redirect()->back()->with('error', 'Student not found.');
        }
    }

    //Sid
    public function viewSid($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();
        return view('admin.viewSid', ['student' => $student]);
    }

    public function editSid($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        return view('admin.editSid', ['student' => $student]);
    }

    public function updateSid(Request $request, $INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();

        if ($student) {
            $student->update($request->all());
            return redirect()->back()->with('success', 'Student updated successfully.');
        } else {
            return redirect()->back()->with('error', 'Student not found.');
        }
    }

    public function socView()
    {
        $students = Student::where('SOC', 1)->get();
        return view('admin.socLayout', ['students' => $students]);
    }

    public function sidView()
    {
        $students = Student::where('SIDD', 1)->get();
        return view('admin.sidLayout', ['students' => $students]);
    }

    //Admission SOC
    public function admissionOfficerViewSoc($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();
        return view('admission.admissionOfficerViewSoc', ['student' => $student]);
    }

    //Admission Sid
    public function admissionOfficerViewSid($INDEX_NO)
    {
        $student = Student::where('INDEX_NO', $INDEX_NO)->first();
        return view('admission.admissionOfficerViewSid', ['student' => $student]);
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/student/confirm-password.blade.php
<x-guest-layout>
    <div class="mb-4 text-sm text-gray-600 dark:text-gray-400">
        {{ __('This is a secure area of the application. Please confirm your password before continuing.') }}
    </div>

    <form method="POST" action="{{ route('password.confirm') }}">
        @csrf

        <div>
            <x-input-label for="password" :value="__('Password')" />

            <x-text-input id="password" class="block mt-1 w-full"
                            type="password"
                            name="password"
                            required autocomplete="current-password" />

            <x-input-error :messages="$errors->get('password')" class="mt-2" />
        </div>

        <div class="flex justify-end mt-4">
            <x-primary-button>
                {{ __('Confirm') }}
            </x-primary-button>
        </div>
    </form>
</x-guest-layout>

resources/views/student/footer.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footer</title>
    <style>
        .site-footer {
                background-color: #1D8348;
                padding: 20px 0 20px;
                font-size: 18px;
                line-height: 24px;
                color: #737373;
                text-align: center;
            }

            .site-footer a {
                color: #737373;
            }

            .site-footer a:hover {
                color: #fff;
                text-decoration: none;
            }

            .copyright-text {
                margin: 0;
                /* color: #ff7f18; */
                color:white;
                font-weight: bold;
            }
    </style>
</head>
<body>
    <footer class="site-footer" style="margin-top: auto;">
        <div class="container">
            <div class="row">
                <div>
                    <p class="copyright-text">Copyright &copy; 2023 CTT Ranking System</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

resources/views/student/forgotpassword.blade.php
<x-guest-layout>
    <x-authentication-card>
        <div>
            <img src="{{ asset('assets/img/logo.jpg') }}" />
        </div>

        <div class="mb-4 text-sm text-gray-600">
            {{ __('Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.') }}
        </div>

        @if (session('status'))
            <div class="mb-4 font-medium text-sm text-green-600">
                {{ session('status') }}
            </div>
        @endif

        <x-validation-errors class="mb-4" />

        <form method="POST" action="{{ route('password.email') }}">
            @csrf

            <div class="block">
                <x-label for="email" value="{{ __('Email') }}" />
                <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required autofocus autocomplete="username" />
            </div>

            <div class="flex items-center justify-end mt-4">
              <a style="margin-right: 40px" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 focus:bg-gray-700 active:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150" href="{{  url('/') }}"> {{ __('Back') }}</a>
                <x-button>
                    {{ __('Email Password Reset Link') }}
                </x-button>
            </div>
        </form>
    </x-authentication-card>
</x-guest-layout>

resources/views/student/heroPage.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Student Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap" rel="stylesheet">

    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/student.css') }}" rel="stylesheet">

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">

</head>

    <body>
        <div class="container-fluid" style="background-color: #1D8348;">
            <div class="row" style="margin-left: 5%;margin-right: 5%;">
                <nav class="navbar navbar-dark navbar-expand-lg py-0">
                    <a href="index.html" class="navbar-brand">
                        <h1 class="text-white fw-bold d-block">CTT<span style="color: #E48310;">Ranking System</span> </h1>
                    </a>
                    <button type="button" class="navbar-toggler me-0" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <form method="POST" action="{{ route('logout') }}" class="collapse navbar-collapse bg-transparent" id="navbarCollapse">
                        @csrf
                        <div  class="navbar-nav ms-auto me-0 mt-0" style="color: #ffffff;">
                            <a href="{{ route('studentDashboard') }}" class="nav-item nav-link">Home</a>
                            <a href="{{ route('creteria') }}" class="nav-item nav-link">Criteria</a>
                            <a href="{{ route('contactUs') }}" class="nav-item nav-link">Contact</a>
                            <a href="#" class="nav-item nav-link" onclick="event.preventDefault(); this.closest('form').submit();">Logout</a>
                        </div>
                    </form>
                </nav>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

        <script src="{{ asset('lib/wow/wow.min.js') }}"></script>
        <script src="{{ asset('lib/easing/easing.min.js') }}"></script>
        <script src="{{ asset('lib/waypoints/waypoints.min.js') }}"></script>
        <script src="{{ asset('lib/owlcarousel/owl.carousel.min.js') }}"></script>

        <script src="{{ asset('js/main.js') }}"></script>

    </body>

</html>

resources/views/student/login.blade.php
<!doctype html>
<html lang="en">

<head>
  <title>Login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
<body>
  <main>
    <section class="d-flex justify-content-center align-items-center"
        style="width: 100%; height: 100vh; margin: 0; padding: 0;
        background: url(../img/4.jpg) center center no-repeat;background-size: cover; ">
        <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5" >
    <div class="row gx-lg-5 align-items-center mb-5" >
      <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
        <div class="card bg-glass" style="height: 400px;">

                <div class="brand_logo_container">
                    <img src="../img/logo.png" class="brand_logo" style="max-height: 400px; width:100%; padding:10px"  alt="Logo">
                </div>
              <h4 class="mt-1 mb-5 pb-1"></h4>

        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
        <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
        <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

        <div class="card bg-glass">
          <div class="card-body px-4 py-5 px-md-5">


            <form method="POST" action="{{ route('login') }}">
                @csrf
                <h4 class="mb-2 text-center" style="margin-top: -30px;">Login to your account</h4>

                @if(Session::has('error'))
                    <div class="alert alert-danger" role="alert">
                        {{ Session::get('error') }}
                    </div>
                @endif

                <!-- Email input -->
                <div class="form-outline mb-4">
                    <label for="email" class="form-label">Email Address</label>
                    <div class="input-group">
                        <span class="input-group-text"><i class="fas fa-at"></i></span>
                        <input type="email" name="email" id="email" class="form-control" placeholder="Email" required/>
                    </div>
                </div>

                <!-- Password input -->
                <div class="form-outline mb-4">
                    <label for="password" class="form-label">Password</label>
                    <div class="input-group">
                        <span class="input-group-text"><i class="fas fa-lock"></i></span>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Password" required />
                        <span class="input-group-text toggle-password" onclick="togglePassword('password')">
                            <i class="fas fa-eye-slash"></i>
                        </span>
                    </div>
                </div>

                <!-- Remember Me and Login Button -->
                <div class="form-group">
                    <p class="small pb-lg-2 d-flex justify-content-between">
                        <a class="text-black-50 text-primary" href="{{ route('Register') }}">Register</a>
                        <a class="text-black-50 text-primary" href="{{ route('forgotpassword') }}">Forgot password?</a>
                    </p>
                </div>
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary btn-outline-light btn-lg px-5 custom-button" type="submit">Login now</button>
                </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>

  <script>
    function togglePassword(inputId) {
        var input = document.getElementById(inputId);
        var eyeSlash = input.parentElement.querySelector('.toggle-password i');

        if (input.type === 'password') {
            input.type = 'text';
            eyeSlash.classList.remove('fa-eye-slash');
            eyeSlash.classList.add('fa-eye');
        } else {
            input.type = 'password';
            eyeSlash.classList.remove('fa-eye');
            eyeSlash.classList.add('fa-eye-slash');
        }
    }
</script>

</body>
</html>